### ISSUE TITLE
BUG - "Attach logo" button in the iFrame does nothing when submitting a new use case on the site

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#60]
When I click the **Attach file** button to upload a company logo, nothing happens.

This only applies to the iFrame version on the website. It's not an issue with new submissions using the direct Airtable form link (https://airtable.com/shrYlu3mjtCiBTlOG).

**REPLICATION STEPS**
1. Go to https://planetcassandra.org/usecases/
2. Click on ADD NEW USE CASE button
3. In the `Company Logo File` field, click on the **Attach file** button.

**ENVIRONMENT**
- Platform - MacOS
- Browser - Google Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**OTHER INFO**
I captured this error in the JavaScript Console:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new r (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/web_client_filepicker_v3_client-4N3QNJAU.js:23:8659)
    at new r (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/web_client_filepicker_v3_client-4N3QNJAU.js:23:9909)
    at new e (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/web_client_filepicker_v3_client-4N3QNJAU.js:23:16940)
    at Ut (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/web_client_filepicker_v3_client-4N3QNJAU.js:23:22062)
    at new ir (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/web_client_filepicker_v3_client-4N3QNJAU.js:23:24946)
    at https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/chunk-3Q2HBD5J.js:373:158343
    at async zci (https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/chunk-3Q2HBD5J.js:800:77534)
    at async https://static.airtable.com/esbuild/by_sha/1a93c562/br/chunks/chunk-3Q2HBD5J.js:800:80581
```

**Comment by allisonnokes** [comment]
I cannot replicate this issue.  Following the replication steps above, I was able to upload an image to the company logo field.  I submitted the form and verified that the logo image I uploaded was indeed stored in the Airtable Submissions table. 

![image](https://github.com/PlanetCassandra/website/assets/91761539/0e783735-a934-418e-8ad6-278483423e63)
![image](https://github.com/PlanetCassandra/website/assets/91761539/6526bd36-fb01-43c8-822d-1a8c1131b798)
![image](https://github.com/PlanetCassandra/website/assets/91761539/5d3aae31-8be5-4398-b24d-4e5c3f778a63)
